# Generated by Django 2.0.1 on 2018-01-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('symbol', models.CharField(max_length=15)),
                ('timeframe', models.CharField(max_length=5)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
            ],
        ),
    ]
